# Generated by Django 2.2.1 on 2019-10-21 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_example2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic1', models.ImageField(upload_to='pic_folder/')),
                ('model_pic2', models.ImageField(upload_to='pic_folder/')),
                ('model_pic3', models.ImageField(upload_to='pic_folder/')),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Imagen',
            },
        ),
    ]
