# Generated by Django 2.1.14 on 2019-11-23 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('lastname', models.CharField(max_length=245)),
                ('age', models.CharField(max_length=245)),
                ('address', models.CharField(max_length=245)),
                ('career', models.CharField(max_length=245)),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
