# Generated by Django 2.1.14 on 2019-11-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
